# NumPy

<table align="left">
  <td>
    <a target="_blank" href="http://nbviewer.ipython.org/github/ShowMeAI-Hub/awesome-AI-cheatsheets/blob/main/Numpy/numpy-cheatsheet-code.ipynb"><img src="https://raw.githubusercontent.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg" />在nbviewer上查看notebook</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/ShowMeAI-Hub/awesome-AI-cheatsheets/blob/main/Numpy/numpy-cheatsheet-code.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" />在Google Colab运行</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets/tree/main/Numpy/numpy-cheatsheet-code.ipynb"><img src="https://badgen.net/badge/open/github/color=cyan?icon=github" />在Github上查看源代码</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets/Numpy/numpy速查表.pdf"><img src="https://badgen.net/badge/download/pdf/color=white?icon=github"/>下载速查表</a>
  </td>
</table>

## 说明
**notebook by [韩信子](https://github.com/HanXinzi-AI)@[ShowMeAI](https://github.com/ShowMeAI-Hub)**

更多AI速查表资料请查看[速查表大全](https://github.com/ShowMeAI-Hub/awesome-AI-cheatsheets)

## 导入工具库

Numpy是Python数据科学计算的核心库，提供了高性能的多维数组对象及处理数组的工具。

使用以下语句导入Numpy库：

In [ ]:
import numpy as np

### Numpy数组

1维数组

2维数组【axis 1  axis 0】

3维数组【axis 2  axis 1  axis 0】

## 创建数组

### 初始化

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [ ]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)

### 特殊数组

In [ ]:
np.zeros((3, 4))   #创建值为0数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2, 3, 4),dtype=np.int16)   #创建值为1数组

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d = np.arange(10, 25, 5)   #创建均匀间隔的数组（步进值）

In [ ]:
np.linspace(0, 2, 9)   #创建均匀间隔的数组（样本数）

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
e = np.full((2, 2), 7)   #创建常数数组

In [ ]:
f = np.eye(2)   #创建2x2单位矩阵

In [ ]:
np.random.random((2, 2))   #创建随机值的数组

array([[0.54217164, 0.25095821],
       [0.40964939, 0.45411324]])

In [ ]:
np.empty((3,2))   #创建空数组

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 输入/输出

### 保存与载入磁盘上的文件

In [ ]:
np.save('my_array', a)

In [ ]:
np.savez('array.npz', a, b)

In [ ]:
np.load('my_array.npy')

array([1, 2, 3])

In [ ]:
np.savetxt("my_array.txt", a, delimiter=" ")

### 保存与载入文本文件

In [ ]:
np.loadtxt("my_array.txt")

array([1., 2., 3.])

In [ ]:
np.genfromtxt("my_array.txt", delimiter=' ')

array([1., 2., 3.])

## 数据类型

**有以下的一些数据类型**

In [ ]:
np.int64   #带符号的64位整数

numpy.int64

In [ ]:
np.float32   #标准双精度浮点数

numpy.float32

In [ ]:
np.complex   #显示为128位浮点数的复数

complex

In [ ]:
np.bool   #布尔值：True值和False值

bool

In [ ]:
np.object   #Python对象

object

In [ ]:
np.string_   #固定长度字符串

numpy.bytes_

In [ ]:
np.unicode_   #固定长度Unicode

numpy.str_

## 数组信息

**查看数组的基本信息**

In [ ]:
a.shape   #数组形状，几行几列

(3,)

In [ ]:
len(a)   #数组长度

3

In [ ]:
b.ndim   #几维数组

2

In [ ]:
e.size   #数组有多少元素

4

In [ ]:
b.dtype   #数据类型

dtype('float64')

In [ ]:
b.dtype.name   #数据类型的名字

'float64'

In [ ]:
b.astype(int)   #数据类型转换

array([[1, 2, 3],
       [4, 5, 6]])

## 数组计算

### 算数运算

In [ ]:
g = a - b   #减法

In [ ]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
np.subtract(a,b)   #减法

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
b + a   #加法

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
np.add(b,a)   #加法

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
a / b   #除法

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
np.divide(a,b)   #除法

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
a * b   #乘法

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
np.multiply(a,b)   #乘法

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
np.exp(b)   #幂

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
np.sqrt(b)   #平方根

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
np.sin(a)   #正弦

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(b)   #余弦

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [ ]:
np.log(a)   #自然对数

array([0.        , 0.69314718, 1.09861229])

In [ ]:
e.dot(f)   #点积

array([[7., 7.],
       [7., 7.]])

### 比较

In [ ]:
a == b   #对比值

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a < 2   #对比值

array([ True, False, False])

In [ ]:
np.array_equal(a, b)   #对比数组

False

### 聚合函数

In [ ]:
a.sum()   #数组汇总

6

In [ ]:
a.min()   #数组最小值

1

In [ ]:
b.max(axis=0)   #数组最大值，按行

array([4., 5., 6.])

In [ ]:
b.cumsum(axis=1)   #数组元素的累加值

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [ ]:
a.mean()   #平均数

2.0

In [ ]:
np.median(b)   #中位数

3.5

In [ ]:
np.corrcoef(a, b)   #相关系数

array([[1.        , 0.98198051, 1.        ],
       [0.98198051, 1.        , 0.98198051],
       [1.        , 0.98198051, 1.        ]])

In [ ]:
np.std(b)   #标准差

1.5920810978785667

## 数组复制

**可以通过copy复制数组**

In [ ]:
h = a.view()   #使用同一数据创建数组视图

In [ ]:
np.copy(a)   #创建数组的副本

array([1, 2, 3])

In [ ]:
h = a.copy()   #创建数组的深度拷贝

## 数组排序

**通过sort进行数组排序**

In [ ]:
a.sort()   #数组排序

In [ ]:
c.sort(axis=0)   #以轴为依据对数组排序

## 子集、切片、索引

### 子集

In [ ]:
a[2]   #选择索引2对应的值

3

In [ ]:
b[1, 2]   #选择行列index为1和2位置对应的值（等同于b[1][2] ）

6.0

### 切片

In [ ]:
a[0:2]   #选择索引为0与1对应的值

array([1, 2])

In [ ]:
b[0:2, 1]   #选择第1列中第0行、第1行的值

array([2., 5.])

In [ ]:
b[:1]   #选择第0行的所有值（等同于b[0:1,:1] ）

array([[1.5, 2. , 3. ]])

In [ ]:
c[1,...]   #等同于 [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [ ]:
a[ : :-1]   #反转数组a

array([3, 2, 1])

In [ ]:
a[a<2]   #选择数组a中所有小于2的值

array([1])

In [ ]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]   #选择(1,0),(0,1),(1,2)和(0,0)所对应的值

array([4. , 2. , 6. , 1.5])

In [ ]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]   #选择矩阵的行列子集

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## 数组操作

### 转置数组

In [ ]:
i = np.transpose(b)   #转置数组

In [ ]:
i.T   #转置数组

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### 改变数组形状

In [ ]:
b.ravel()   #拉平数组

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
g.reshape(3, -2)   #改变数组形状，但不改变数据

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

### 添加或删除值

In [ ]:
h.resize((2, 6))   #返回形状为(2,6)的新数组

In [ ]:
np.append(h, g)   #追加数据

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [ ]:
np.insert(a, 1, 5)   #插入数据

array([1, 5, 2, 3])

In [ ]:
np.delete(a, [1])   #删除数据

array([1, 3])

### 合并数组

In [ ]:
np.concatenate((a, d), axis=0)   #拼接数组

array([ 1,  2,  3, 10, 15, 20])

In [ ]:
np.vstack((a, b))   #纵向以行的维度堆叠数组

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
np.r_[e, f]   #纵向以行的维度堆叠数组

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [ ]:
np.hstack((e, f))   #横向以列的维度堆叠数组

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [ ]:
np.column_stack((a,d))   #以列的维度创建堆叠数组

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
np.c_[a, d]   #以列的维度创建堆叠数组

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### 分割数组

In [ ]:
np.hsplit(a, 3)   #纵向分割数组为3等份

[array([1]), array([2]), array([3])]

In [ ]:
np.vsplit(c,2)   #横向分割数组为2等份

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]

## 调用帮助

**通过info函数调用帮助信息**

In [ ]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
